name: Check Publication Date and Run Progression

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
    
    - name: Get current month's publication date
      id: get_date
      run: |
        python -c "
        import requests
        from bs4 import BeautifulSoup
        from datetime import datetime
        
        # Get the webpage content
        url = 'https://www.fftt.com/site/articles/calendrier-publications'
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Find the table with publication dates
        table = soup.find('table')
        if table:
            # Find all rows in the table
            rows = table.find_all('tr')
            for row in rows:
                # Look for the row containing 'Non Premium'
                if 'Non Premium' in row.text:
                    # Get all cells in this row
                    cells = row.find_all('td')
                    # May is in the 9th column (index 8)
                    if len(cells) > 8:
                        date_cell = cells[8]
                        if date_cell:
                            date_text = date_cell.text.strip()
                            # Extract just the date part (e.g., '13 Mai' -> '13 Mai')
                            date_text = date_text.split('.')[0].strip()
                            print(f'::set-output name=pub_date::{date_text}')
                            break
        "
    
    - name: Check if we should run progression script
      id: check_date
      run: |
        # Get the publication date from previous step
        pub_date="${{ steps.get_date.outputs.pub_date }}"
        echo $pub_date
        
        # Convert to datetime
        pub_datetime=$(date -d "$pub_date" +%s)
        echo $pub_datetime
        
        # Get tomorrow's date
        tomorrow=$(date -d "2025-05-13" +%s)
        echo $tomorrow
        
        # Compare dates
        if [ $pub_datetime -eq $tomorrow ]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run progression script
      if: steps.check_date.outputs.should_run == 'true'
      run: |
        python query_monthly_progression.py 