name: Check Publication Date and Run Progression

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
    
    - name: Get current month's publication date
      id: get_date
      run: |
        python -c "
        import requests
        from bs4 import BeautifulSoup
        from datetime import datetime
        
        # Get the webpage content
        url = 'https://www.fftt.com/site/articles/calendrier-publications'
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        # Find the table with publication dates
        table = soup.find('table')
        if table:
            # Get current month
            current_month = datetime.now().month
            
            # Find the row for non-premium users
            rows = table.find_all('tr')
            for row in rows:
                cells = row.find_all('td')
                if len(cells) > 1 and 'Non Premium' in row.text:
                    # Get the date for current month (index 0-based)
                    date_cell = cells[current_month]
                    if date_cell:
                        date_text = date_cell.text.strip()
                        print(f'::set-output name=pub_date::{date_text}')
                        break
        "
    
    - name: Check if we should run progression script
      id: check_date
      run: |
        # Get the publication date from previous step
        pub_date="${{ steps.get_date.outputs.pub_date }}"
        
        # Convert to datetime
        pub_datetime=$(date -d "$pub_date" +%s)
        
        # Get tomorrow's date
        tomorrow=$(date -d "2025-05-13" +%s)
        
        # Compare dates
        if [ $pub_datetime -eq $tomorrow ]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run progression script
      if: steps.check_date.outputs.should_run == 'true'
      run: |
        python query_monthly_progression.py 