name: Check Publication Date and Run Progression

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Get current month's publication date
      id: get_date
      run: |
        PUB_DATE=$(python -c "from query_monthly_progression import PingPocketQuery; print(PingPocketQuery.get_publication_date())")
        echo "pub_date=$PUB_DATE" >> $GITHUB_OUTPUT
    
    - name: Check if we should run progression script
      id: check_date
      run: |
        # Get the publication date from previous step
        pub_date="${{ steps.get_date.outputs.pub_date }}"
        
        # Convert to datetime
        pub_datetime=$(date -d "$pub_date" +%s)
        
        # Get yesterday's date
        yesterday=$(date -d "2025-05-13" +%s)
        
        # Compare dates
        if [ $pub_datetime -eq $yesterday ]; then
          echo "should_run=true" >> $GITHUB_OUTPUT
        else
          echo "should_run=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run progression script
      if: steps.check_date.outputs.should_run == 'true'
      run: |
        python query_monthly_progression.py 